describe("rtp_nvim", function()
    local rtp = require("rtp_nvim")
    local fixture_dir = vim.fs.joinpath(vim.fn.getcwd(), "spec", "fixtures")
    it("sources plugin scripts multiple times and ftdetect scripts once", function()
        assert.is_nil(vim.g.test_plugin)
        assert.is_nil(vim.g.test_ftdetect)
        assert.is_nil(vim.g.test_after_plugin)
        rtp.source_rtp_dir(fixture_dir)
        assert.same(1, vim.g.test_plugin)
        assert.same(1, vim.g.test_ftdetect)
        rtp.source_rtp_dir(fixture_dir)
        assert.same(2, vim.g.test_plugin)
        assert.same(1, vim.g.test_ftdetect)
        rtp.source_after_plugin_dir(fixture_dir)
        assert.same(1, vim.g.test_after_plugin)
        rtp.source_after_plugin_dir(fixture_dir)
        assert.same(2, vim.g.test_after_plugin)
    end)
end)
